### ISSUE TITLE
Edit user details

### ISSUE THREAD

**Issue by Pryx** [Pryx/server-status#10]
Another nice feature to have would be to edit Name, Surname and Username... Should be easy enough 🙂

**Comment by PeterFleurkens** [comment]
The Name and surname works now. But can we change the username in the settings too without editing in MySQL.

**Comment by Pryx** [comment]
It is planned, yes, but unfortunately @Arascog has a eye infection and I don't have that much time because of school so it will have to wait a bit.

**Comment by PeterFleurkens** [comment]
Take your time :)
