### ISSUE TITLE
People Contributing

### ISSUE THREAD

**Issue by yigitkeremoktay** [Pryx/server-status#105]
As I can see there are a lot of people wanting to contribute.
I would also like to help too. It's a prefect and simple project. 
Actually you could allow anyone by creating Slack or Discord Group. 
It is a really nice project and it should not die.

**Comment by SigmaScorpii** [comment]
@Pryx I think this idea should be approved.
That way, people who have less time can also contribute in an easier way.
I'd recommend Discord, not really for privacy, more for ease of use for most people as they might have discord at boot up on their pc.

**Comment by yigitkeremoktay** [comment]
@SigmaScorpii Sure not for privacy. Discord feels a bit childish. That is why I recommended Slack it feels a bit more professional.
If he can't get it to work I will create a fork and create a group myself.

**Comment by Pryx** [comment]
I think this is a great idea! I'm not opposed to either choice, I might slightly prefer Discord though - just because I had issues with multiple workspaces on Slack. I wonder if anyone else wants to weigh in? ( @jhuesser @thnilsen @ChipX0 come to mind)

**Comment by jhuesser** [comment]
I mostly won't be able to contribute in the short future. Maybe again at a later day. I think it would be nice to have a chat platform for all contributors. I also prefer discord over slack.

**Comment by yigitkeremoktay** [comment]
OK then, Process is simple from now on. You will create an empty discord server (@Pryx ) you will link it in your project readme. Then We can help you get roles and channels and stuff. Or if you want I can create the server too. Just let me know if you need to!
(@jhuesser Although you can't contribute it would be nice to have you there.)

**Comment by yigitkeremoktay** [comment]
> I wonder if anyone else wants to weigh in? ( @jhuesser @thnilsen @Chipx0 come to mind)
I linked it in #96 to have people come in. There were people wanting to contribute.

**Comment by thnilsen** [comment]
Sounds like a good initiative. If the majority favors Discord, then use that.

**Comment by Pryx** [comment]
So, I created a discord server, will update readme soon :slightly_smiling_face: 

In the meantime here is the link: https://discord.gg/F9nXmE

**Comment by yigitkeremoktay** [comment]
@Pryx it is invalid. You need to update the link :)

**Comment by jhuesser** [comment]
Hmm, I could join without issues.

**Comment by yigitkeremoktay** [comment]
@jhuesser it is timed out, it has a time limit. You can send a link again

**Comment by jhuesser** [comment]
This one never expires: https://discord.gg/Wgxnxz4

**Comment by yigitkeremoktay** [comment]
This issue is now closed. @Pryx Please add the link to discord group in readme.md if possible
