### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by SigmaScorpii** [Pryx/server-status#12]
I've just finished the Dutch translation for this repo.
I'll try to translate it to another language as well, or at least a part of it.

**Comment by Pryx** [comment]
Thank you for your help 🙂 I've added you to the list of contributors and added the translation files. Feel free to translate to any language you are able to translate to

**Comment by SigmaScorpii** [comment]
I've just updated the Dutch translation.
New untranslated tags have now been translated.

**Comment by Pryx** [comment]
Thanks!

**Comment by SigmaScorpii** [comment]
I've updated the Dutch translation again to contain the new added strings.
This can be found on poeditor.
