### ISSUE TITLE
Error 500 on Installation

### ISSUE THREAD

**Issue by SpegalDev** [Pryx/server-status#177]
![image](https://github.com/server-status-project/server-status/assets/133661004/e43921fa-bbc9-424a-9ad3-f30194d99fe7)

Fill out the information on the install page, then it immediately goes into a 500 error. Using PHP 7.4.

https://status.spegal.dev

**Comment by jhuesser** [comment]
Can sou please show us the log files of your webserver?

**Comment by SpegalDev** [comment]
Unfortunately I'm not getting any errors logged.

**Comment by jhuesser** [comment]
Without webserver error logs it‘s unfortunately not possible to troubleshoot server side issues. Is this reproducible on a different webserver?Am 08.05.2024 um 17:24 schrieb SpegalDev ***@***.***>:﻿
Unfortunately I'm not getting any errors logged.

**Comment by SpegalDev** [comment]
Ended up being able to get it working on another server of mine. Had to jump through quite a few hoops to get the MySQL to install properly. Kept getting errors about byte limit 767, even though I had 'innodb_large_prefix' set to ON.
