### ISSUE TITLE
Cannot add new users

### ISSUE THREAD

**Issue by cyberzombie16** [Pryx/server-status#24]
When i fill out the form for a new user and click submit, it doesn't create the user in the database.

**Comment by Pryx** [comment]
Hi, thank you for reporting it, will fix it ASAP.

**Comment by Pryx** [comment]
@cyberzombie16 please report if it's fixed, when testing locally a typo was the only problem

**Comment by cyberzombie16** [comment]
@Pryx Yes, It is fixed. Thank you!
