### ISSUE TITLE
Fix Admin Login Bug

### ISSUE THREAD

**Issue by AlexanderEDavis** [Pryx/server-status#35]
Hi. I don't know if it's my server of the app but I get the followi8ng PHP error 500 whenever I login to the administration area:

[13-May-2018 15:47:50 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/alexand2/ServiceStatus/classes/constellation.php:129
Stack trace:
#0 /home/alexand2/ServiceStatus/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1526222870)
#1 /home/alexand2/ServiceStatus/index.php(41): Constellation->render_incidents(true, 0)
#2 {main}
  thrown in /home/alexand2/ServiceStatus/classes/constellation.php on line 129
[13-May-2018 15:47:54 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/alexand2/ServiceStatus/classes/constellation.php:129
Stack trace:
#0 /home/alexand2/ServiceStatus/classes/constellation.php(30): Constellation->get_incidents(true, 0, 6, 1526222874)
#1 /home/alexand2/ServiceStatus/index.php(41): Constellation->render_incidents(true, 0)
#2 {main}
  thrown in /home/alexand2/ServiceStatus/classes/constellation.php on line 129

**Comment by Pryx** [comment]
Hi, thank you for reporting it! I suspect you did a clean install and there are no incidents yet? This might've been introduced by 4b7d8be - can you check whether the older release (1.0.1) works correctly? If it does you can use that in the meantime. No need to do clean install, just replace the files (dont forget to delete install.php). Thanks.

**Comment by Pryx** [comment]
Just tested with the demo page and it looks ok even without any incidents so it is probably not bug in the code but actually server configuration. Do you have MySQL Native Driver (mysqlnd)? It seems that without it the `mysqli_stmt::get_result()` method is not available. This might be good to work around in the future.

**Comment by AlexanderEDavis** [comment]
I tried with the 1.0.1 release and I still have the same error. I'm not too sure if the web server has  MySQL Native Driver installed so I shall check with the hosting company.

**Comment by AlexanderEDavis** [comment]
I just checked. mysqlnd is installed and enabled. We are also running PHP version 7.2. Could this be causing the error?

**Comment by AlexanderEDavis** [comment]
I figured out a fix. Just for your information for cPanel users this is what is needed for the site to work:
![image](https://user-images.githubusercontent.com/9097891/39969638-ac2ad05a-56d6-11e8-9597-9bb395431b3e.png)

**Comment by Pryx** [comment]
Could you please write a quick guide where to find these settings so I can put it in the wiki? Thanks 🙂
