### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by Pryx** [Pryx/server-status#38]

**Comment by jhuesser** [comment]
I'm working on a policy at my fork. will create a PR once finished.

**Comment by Pryx** [comment]
Thanks, that will be really helpful! Do you think you could make it translatable?

**Comment by jhuesser** [comment]
I will provide an english one. I have to re-read all the stuff about translations first.

**Comment by Pryx** [comment]
English is perfect - I will put it on POEditor for translations, just put the content into gettext functions :slightly_smiling_face:

**Comment by jhuesser** [comment]
You mean like this?
```php
echo _$("my text");
```

done that everywhere (in privacy policy and #37 )

**Comment by Pryx** [comment]
Yeah exactly! Thanks, translated privacy policy will be really cool :+1:
