### ISSUE TITLE
Error: in responsive mode title hide

### ISSUE THREAD

**Issue by darkban** [Pryx/server-status#45]
Guys there's another problem ... in responsive mode the title disappears and shows only the icon

![cattura](https://user-images.githubusercontent.com/32014414/42514899-c3e01fbe-845a-11e8-91ed-4abfb52358a4.PNG)

![cattura1](https://user-images.githubusercontent.com/32014414/42514900-c40419e6-845a-11e8-8769-9c70bde13975.PNG)

**Comment by Pryx** [comment]
This is actually intended behavior as there will be menu on the right hand side in future (as it is already on the admin page) and fitting the text in would be painful. Is the text really needed on a smartphone-sized website? I personally don't think it is.

**Comment by Pryx** [comment]
Will not change this as I feel the current behavior is better. If you want the title to show just delete the `hidden-xs` class :slightly_smiling_face: https://github.com/Pryx/server-status/blob/ac8fcc513136815dcf4f214db822d0e6252491a6/template.php#L51
