### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by darkban** [Pryx/server-status#47]
How can I change the background color of this button?

![schermata a 2018-07-13 00-25-43](https://user-images.githubusercontent.com/32014414/42662866-7f670034-8633-11e8-9f66-eec6928e2921.png)

**Comment by Pryx** [comment]
You have to use css, if you have basic coding skills it should be easily doable. If you do not, just take look at here and change things regarding to dropdown https://github.com/Pryx/server-status/blob/ac8fcc513136815dcf4f214db822d0e6252491a6/css/main.css#L566

**Comment by Pryx** [comment]
@darkban were you successful or do you need more guidance?
