### ISSUE TITLE
Incident reporting form validation issue 

### ISSUE THREAD

**Issue by navneetgupta87** [Pryx/server-status#54]
When you enter a new incident, first select 'planned maintenance' and select start date but not end time. then change the type to major outage. This will hide the time options but validation error for end time still appear on submit.

You will have to re-select 'planned maintenance' and then empty start time and then re-select major outage then submit. 

Please undo start time / end time options on change of incident type.

**Comment by Pryx** [comment]
Good catch, thanks for reporting it, will fix asap
