### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by petrk94** [Pryx/server-status#56]
Hello,

I would like to know how to update?
Is there already some mechanism?

I wrote before a updater bash script for phpservermon https://github.com/phpservermon/phpservermon/pull/620

Maybe this could be adapted?

**Comment by Pryx** [comment]
There is not yet any update mechanism but it is planned (#18). Right now the only way is overwrite the old files with new ones and add whatever config constants were added in the new releases.

**Comment by Pryx** [comment]
Bash script could be useful but not quite what I'm planning - I would love to have automatic PHP update script that would notify user in the admin interface and let him upgrade automatically - something like Wordpress has.

**Comment by petrk94** [comment]
Alright, I will wait for the release of the update mechanism :) 
Just thought the bash update script could overbridge the time until the final update mechanism is finished.
When it will be?

**Comment by Pryx** [comment]
It will be in the 1.1.0 release which *should* be at the end of this month :)
