### ISSUE TITLE
admin page?

### ISSUE THREAD

**Issue by MikkelDK** [Pryx/server-status#57]
Hi.

is there adminpage on the server-status system`?

**Comment by petrk94** [comment]
Hi, 
yes there is a admin page.
You can reach it like this: https://server-status.de/admin/

**Comment by MikkelDK** [comment]
hi again.

Does it too supporting webhooks/twitter e.g?

**Comment by Pryx** [comment]
Hi, sorry for late response, the information @petrk94 gave you is indeed correct :slightly_smiling_face: 

Webhooks are not yet supported, but it is definitely planned (#2)

**Comment by MikkelDK** [comment]
@Pryx - so there can be planned for supporting webhooks and twitter (in the future?) cool. thanks! ;)
