### ISSUE TITLE
Http Error 500

### ISSUE THREAD

**Issue by SigmaScorpii** [Pryx/server-status#6]
Hello,

I've successfully downloaded and uploaded your status page source.
Sadly enough, whenever I run the installer I get the error 
"This page isn’t working
status.otuts.eu is currently unable to handle this request.
HTTP ERROR 500 "
Refreshing the page brings me back to the install page.

I tried removing and using another new database and reupload the filles, but the error is still there.
I'm using a paid webhosting with PHP/MySQL.

**Comment by Pryx** [comment]
Hi,
thanks for reporting that. Do you know your PHP & MYSQL version? I've tested it on PHP 7 and MYSQL 5.7 so there might be features that are not supported in PHP 5.X. Also error 500 often means that error reporting is not enabled, you might have error log somewere or it should be possible to enable error reporting somewhere in webhosting administration.

**Comment by SigmaScorpii** [comment]
I took a look at the versions they're using.
They have PHP Version 5.6.32, and MySQL 5.6.38.

I've put the error code in the txt file:
[error log.txt](https://github.com/Pryx/server-status/files/1628468/error.log.txt)

**Comment by Pryx** [comment]
Thank you for that, I'm going to run a compatibility check on the entire repo and going to release fixed version soon.

**Comment by Pryx** [comment]
Should be fixed now, if not please report here again 🙂
