### ISSUE TITLE
HTTPS redirect? Tried removing not working.

### ISSUE THREAD

**Issue by flamelier** [Pryx/server-status#60]
My site doesn't have HTTPS it keeps pulling HTTPS for the site when I got to the folder I have this installed in. I tried editing/removing .htacess and web.config and it isnt helping/working. Still getting that redirect.

Example:
http://example.com/status becomes https://example.com/status

**Comment by Pryx** [comment]
If you delete .htaccess and web.config then you shouldn't be redirected at all - there is absolutely no other code that could be doing that. If you have your status page in a subdir, please check root dir for htaccess too - if you do redirecting to HTTPS on example.com then example.com/status will be probably affected to.

**Comment by flamelier** [comment]
Got it. I had already done what you suggested, The server went through a restart and it fixed it. It was just that subdir that was the issue.

**Comment by Pryx** [comment]
Oh, that is certainly possible. What kind of server was that? A Linux or Windows one?

**Comment by SashaShtal** [comment]
I have the same issue, but my status page is situated on http://status.mysite.com, and when i redirected to https, im getting page like on the screenshot below:
![image](https://user-images.githubusercontent.com/51839212/166605159-9f582c67-7225-4b18-9bac-7a875817731b.png)

**Comment by flamelier** [comment]
> Oh, that is certainly possible. What kind of server was that? A Linux or Windows one?

Linux I believe.
