### ISSUE TITLE
Translation of service status not working properly?

### ISSUE THREAD

**Issue by thnilsen** [Pryx/server-status#64]
Not 100% sure if this is an actual issue or not, but it looks like it is at least for PHP 5.6 and 7.1 running on Centos 7 which I have tested on. Certain strings are not translated. You very kindly merged #63 which fixed the overall status translation, but I  missed the translation of the service status. I guess this could also be the reason for #62...

The code change required for proper status translation is ceea6719652c32135d5ba7dabb57083a905c5cc2. 

However, I see that for the demo site these sections are translated correctly, which makes me be a bit unsure. 

This is what it looks like before d06f42d64dd715532b4b60fc00968e30e8989d1c
![image](https://user-images.githubusercontent.com/10619272/48056539-4a31b500-e1b2-11e8-9629-8ec017d25c29.png)

This is what it looks like with d06f42d64dd715532b4b60fc00968e30e8989d1c and ceea6719652c32135d5ba7dabb57083a905c5cc2.
![image](https://user-images.githubusercontent.com/10619272/48056934-1f942c00-e1b3-11e8-8503-efd09b79117e.png)

**Comment by Pryx** [comment]
That looks weird as that change *should not* be required. I have an idea what could be causing it and will try to confirm later this evening and hopefully push a proper fix.

**Comment by thnilsen** [comment]
I found the reason why the default page fails to translate certain parts. The config.php is being included too late in the script. Commit 3eccbf529e374db78e87625909b2b8d63eeea6f8 fixes this issue. 

On my Ubuntu 18.04 home server I also had to add the following to the setlocale section in order for any translation using _("...") to work. This might be the case for others as well..

`putenv('LANGUAGE='.$_SESSION['locale'].'.UTF-8');`

**Comment by Pryx** [comment]
@thnilsen this is fixed now, right?

**Comment by thnilsen** [comment]
We have fixes for this issue, but it is not in the master. This fix is part of the email subscription PR #71. 
I will create a separate PR for this issue as the email subscription PR is being improved upon. This new PR should also cover #80  and #84 to the extent where the translations exists.
