### ISSUE TITLE
Add impacted services to incident view

### ISSUE THREAD

**Issue by thnilsen** [Pryx/server-status#69]
With the current incident layout it is impossible to see which services the incident is impacting, unless it is written as part of the incident text.

I would suggest that a section is added to each incident to list all services linked to the incident. 
![image](https://user-images.githubusercontent.com/10619272/48693465-d47a1000-ebd9-11e8-97b9-27a74711817d.png)

Commit c75f83c2efab022b780e2d2d375e4b119fca5ed2 is a possible solution to display this data.

**Comment by thnilsen** [comment]
I will make the change to replace "poster by". 
The other part I think we could do better is how the services are fetched per incident. Would it make sense to have that data included as part of the constellation->get_incidents() class? Would save having to do more sql calls to fetch service ids and names outside of the get_incidents() function.

**Comment by thnilsen** [comment]
Code changed. As you will see from the code I also added service_id and service_name to the Incident class to avoid having to manually get the data. I hope it makes sense.

![image](https://user-images.githubusercontent.com/10619272/48833328-640af480-ed7b-11e8-9d1e-2299fec9c962.png)

**Comment by Pryx** [comment]
Looks neat, looking forward to a PR!
