### ISSUE TITLE
Change incident view on frontpage to add date header

### ISSUE THREAD

**Issue by thnilsen** [Pryx/server-status#73]
Is this of any interest to include? 

I have made a small commit that alters the view of incidents on the front page. The commit is 4efd08ffc36a939f6e45420313b362ff99087e5f. It adds a date header to each day there is an incident, and one days without incidents it will show the date header and a subtext of "No reported incidents".

The reasoning behind adding this is that it could be a bit difficult to quickly see what date an incident was reported on using the  x days/months ago view. This is also how a lot of other similar packages resolves the data. 

I'm not sure I have found the best way to calculate and render this, but at the moment I could not come up with any other way without changing the entire render function. 
The way to check if the user is on the admin page should probably be looked at too, but it isn't enough to check for the boolean $admin since this is not set if the end user clicks on the "Load more" button.
![image](https://user-images.githubusercontent.com/10619272/49462555-a3fbbe00-f7f6-11e8-86ee-af504ba28bf0.png)

**Comment by Pryx** [comment]
This is a nice touch, thanks! I'd love to see option to leave the dates with no recorded incidents omitted before merging this 🙂

**Comment by Pryx** [comment]
I don't see a problem with it although maybe writing a getter would be a better approach IMO. I will take a proper look when you make a PR 🙂

**Comment by yigitkeremoktay** [comment]
@thnilsen Please close this issue as it was cancelled in one of our commits. Thank You!

**Comment by thnilsen** [comment]
Closing as the assosciated PR #74  has been canceled. The implementation needs re-thinking.
