### ISSUE TITLE
/admin/POLICY_URL -Page Not Found

### ISSUE THREAD

**Issue by SigmaScorpii** [Pryx/server-status#77]
So I just updated the status panel I'm running with the most recent version.
This activated the "Imprint & Privacy Policy" page.

However, when you try to open the file it displays an error 404 page.
You can view the issue live at https://status.otuts.eu/

Is there some config feature I missed?
Since I can't find anything in the settings page.

Kind Regards,

**Comment by SigmaScorpii** [comment]
Update of the issue:
I manually edited the "config.php" with the "config.php.template".
This solved my issue.

But this raised another question:
I always override all the files expect the "config.php" as it contains the Database connection details.
Are there other filles which aren't overwritting that should be sometimes?

**Comment by Pryx** [comment]
Only config should be updated manually :) Hopefully I will get some time between school and work to work on settings in database so that upgrading config.php will no longer be necessary :slightly_smiling_face:
