### ISSUE TITLE
Installer fails to create config.php

### ISSUE THREAD

**Issue by SigmaScorpii** [Pryx/server-status#78]
Okay, so, it doesn't exactly fail.
But it makes an issue.

I had to do a fresh install because I might have destroyed some things in the database. (Which I can't either deny or confirm).
But after the clean installation, the page fails to load the status page.

I did some digging to find that the config creates an extra " ' " which destroys the config.php and causes the status page to fail.
I've attached a screenshot to show what I mean.
![2019-02-11 3](https://user-images.githubusercontent.com/35401436/52586832-cb938600-2e38-11e9-8dc0-0a50594b2fe9.png)

**Comment by Pryx** [comment]
Hi, sorry for not responding sooner, I will take a look ASAP, hopefully as soon as friday afternoon :slightly_smiling_face: I'm finally not so busy at school so I can start developing this project again :slightly_smiling_face:
