### ISSUE TITLE
Languagevariables

### ISSUE THREAD

**Issue by derrobin154** [Pryx/server-status#80]
Hello,
In the following pages the texts are displayed in English despite German language.

- index.php (Status [Major outage, etc.], Incidents [Impacted Services], Footer [Imprint & Privacy Policy])
- admin/index.php (Incidents [Impacted Services], Footer [Imprint & Privacy Policy])
- admin/settings (Services [In German is "Name" shown as "Vorname" but this is the Translation for "Surname"], User ["active" must be "Aktiv"])

Greetings.

**Comment by thnilsen** [comment]
@derrobin154 This issue is also reported in #64 with a suggested solution. The inclusion of template.php needs to come after config.php is loaded.

If you are using master or one of the published relases, you can modify index.php like this:
Current code:
```
require_once("template.php");
if (!file_exists("config.php"))
{
  require_once("install.php");
}
else{
require_once("config.php");
require_once("classes/constellation.php");
```  

Change to:
``` 
if (!file_exists("config.php"))
{
 require_once("template.php"); 
 require_once("install.php");
}
else{
require_once("config.php");
require_once("template.php");
require_once("classes/constellation.php");
`

**Comment by derrobin154** [comment]
Thanks, but the only was changed is the Language in the Status [Major outage, etc.] Imprint and the other is on English.

**Comment by thnilsen** [comment]
It doesn't look like the text string "Imprint & Privacy Policy" is translated in the DE language file. Add the translation to the DE .po file and recompile and it should show up in your local language.
To recompile the file after a change use the following command:

`msgfmt -o locale/de_DE/LC_MESSAGES/server-status.po locale/de_DE/LC_MESSAGES/server-status.mo`

You will have to restart the web server after updating the mo file.

**Comment by derrobin154** [comment]
msgfmt under Linux? the Page is Running on a Webspace.

**Comment by thnilsen** [comment]
Use an online converter like https://po2mo.net/ to generate the MO file.

**Comment by derrobin154** [comment]
As soon as I do, he shows me the whole text in English, looks like he won't accept the language file.

**Comment by thnilsen** [comment]
I have sent you an email to your gmail account. Send me the PO file with the correct translations and I'll generate the MO file and send it back.
