### ISSUE TITLE
Installation url 

### ISSUE THREAD

**Issue by ruudjutinant** [Pryx/server-status#88]
I have started with docker.

I very confused a field url in "Website details".
it's a required field and it have to be a type url , 
but when I try the url like **"http://localhost"** then the page will redirect me to Current status then everything pointing to something like http://localhost/http%3A%2F%2Flocalhost/favicon/manifest.json (a static file)

please help! thank you.

**Comment by ruudjutinant** [comment]
I fix it, after installation success. I edit the file config.php field URL to an empty string and it works.

so I design to fix source code by remove URL validation.

if you have any better solution lets me know, Thank you.

**Comment by Pryx** [comment]
Hi, sorry for the late reply. I'm gonna reopen the issue for now as I have a major rewrite of the code planned and will have to take this into consideration :)

**Comment by thnilsen** [comment]
I believe this issue is also covered by PR #101.
