### ISSUE TITLE
page setup missing

### ISSUE THREAD

**Issue by alanpoux** [Pryx/server-status#91]
Hi, I've tried to install the server status, the config page are ikay, everything works fine but at the moment that I've finished setup, the page load like without the CSS, only texts 

![image](https://user-images.githubusercontent.com/12087607/69888369-be725580-12eb-11ea-8b2f-d0498ca48622.png)

**Comment by Pryx** [comment]
Hi, sorry for late reply. Can you post your config file - the `WEB_URL` in particular? It should look like this `define("WEB_URL", "http://192.168.1.66/state"); //Used for links ` - if it does not, try changing it.

**Comment by KnuffelBeestje** [comment]
Same issue here:
`define("WEB_URL", "https%3A%2F%2Flaunchstatus.wracked.nl%2Fstatus"); //Used for links `

**Comment by thnilsen** [comment]
The calls to urlencode() in install.php code should be removed for the two URL config options (url and policy_url). I see very few benefits from having these two parameters checked during installation. This would resolve #81, #91, #94 and #95.

 @Pryx Do you want me to make up a quick PR?

**Comment by Pryx** [comment]
Resolved by #101
