### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by arkhalid1986** [Pryx/server-status#95]
Hello,

I am trying to install https://sub-domain/install.php after filling up all information when i hit the RUN INSTALL Button i am getting this error 
Connection failed: php_network_getaddresses: getaddrinfo failed: Name or service not known

I don't know what kind of ERROR is this. Please let me know and help me to install

**Comment by arkhalid1986** [comment]
Installation problem resolved. NOw new issue come up when i am trying to access admin area i am getting this error.

This page isn’t working
domain is currently unable to handle this request.
HTTP ERROR 500

I don't know what is this.

**Comment by Pryx** [comment]
Resolved by #101
