### ISSUE TITLE
How to start the site

### ISSUE THREAD

**Issue by pandagreydev** [Pryx/server-status#98]
Hello, I'm a PHP beginner and I don't know how to start the site on a Windows VPS. Can you help me?

**Comment by SigmaScorpii** [comment]
Hi pandagreydev,

It's very simply.
You just need something like XAMPP. (https://www.apachefriends.org/index.html)

Download, install and configure what you need. (Which would be the following for this status panel: SQL, PHP and Apache).
After that, simply download this panel, drop it in "Public_html" or "WWW" depending on the software.
Start your web software through it's control panel.

Then simply navigate to localhost/<location of status panel> .
Follow the configuration wizard and you're ready to go.


If you need more help with a specific step in this process, feel free to ask! :)

**Comment by Pryx** [comment]
@pandagreydev did @SigmaScorpii answer your question? :)

**Comment by Pryx** [comment]
Closing, please let me know if you need further assistance :slightly_smiling_face:
